backend:
  name: github
  repo: nioc/test-hugo
  branch: master
  automatic_deployments: false
  base_url: https://sveltia-cms-authenticator.dev-c5f.workers.dev
publish_mode: editorial_workflow
media_folder: static/images/uploads
public_folder: /images/uploads
site_url: https://test-hugo.nioc.eu
locale: fr
collections:
  - name: post
    label: Articles
    label_singular: Article
    folder: content/posts
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: Layout, name: layout, widget: hidden, default: blog }
      - { label: Titre, name: title, widget: string }
      - { label: Brouillon, name: draft, widget: boolean, default: true }
      - { label: Date de publication, name: date, widget: datetime }
      - { label: Description, name: description, widget: string }
      - { label: Image de titre, name: thumbnail, widget: image, required: false }
      - { label: Contenu, name: body, widget: markdown }
      - { label: Tags, name: tags, widget: list, default: ["dev"], label_singular: Ajouter, allow_add: false, collapsed: true }
  - name: pages
    label: Pages
    icon: info
    label_singular: Page
    description: Pages statiques
    files:
      - name: about
        label: A propos
        file: content/about/_index.md
        fields:
          - { label: Type, name: type, widget: hidden, default: page }
          - { label: Menu, name: menu, widget: hidden, default: main }
          - { label: Titre, name: title, widget: string, hint: Titre de la page }
          - { label: Description, name: description, widget: string, required: false, hint: Sous titre de la page }
          - { label: Contenu, name: body, widget: markdown, hint: Contenu }
